version: "3.9"

services:
  db:
    image: postgres
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678Sv
      POSTGRES_DB: mydb
    ports:
      - 5436:5432
